all: risk-assessment.pdf deconfliction.pdf remote-id.pdf

risk-assessment.pdf: risk-assessment.lyx
	lyx --export pdf2 risk-assessment.lyx

deconfliction.pdf: deconfliction.lyx
	lyx --export pdf2 deconfliction.lyx

remote-id.pdf: remote-id.lyx
	lyx --export pdf2 remote-id.lyx